

--Q1) What is the total revenue generated by the male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM c_retails
GROUP BY gender;

--Q2) which customers used a discount but still spent more than the average amount?
SELECT * FROM c_retails;
SELECT customer_id, purchase_amount
FROM c_retails
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM c_retails);

--Q3) Which are the Top 5 products with the highest average review rating.
SELECT * FROM c_retails;
SELECT item_purchased, ROUND(AVG(review_rating :: numeric),2) AS highest_avg
FROM c_retails
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4) Compare the average purchased amounts between Standard and Express shipping.
SELECT * FROM c_retails;
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM c_retails
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

--Q5) Do Subscribed customers spend more? Compare Average spend and total revenue between subscribers and non-subscribers.
SELECT * FROM c_retails;
SELECT subscription_status, COUNT(purchase_amount), ROUND(AVG(purchase_amount), 2) AS average_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM c_retails
GROUP BY subscription_status
ORDER BY total_revenue, average_spend desc;

--Q6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT * FROM c_retails;
SELECT item_purchased,
100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*) as discount_rate
FROM c_retails
GROUP BY item_purchased 
ORDER BY discount_rate DESC
limit 5;

--Q7) Segments customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment.
SELECT * FROM c_retails;

WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM c_retails
)

SELECT customer_segment, COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--Q8) What are the top 3 most purchased products within each category?
--Q8) What are the top 3 most purchased products within each category?
SELECT * FROM c_retails

WITH item_count as (
SELECT category, item_purchased, COUNT(customer_id) as total_orders, 
ROW_NUMBER() over(partition by category order by COUNT(customer_id) DESC) as item_rank
FROM c_retails
Group by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders 
FROM item_count
WHERE item_rank <= 3;

--Q9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECt * FROM c_retails;


SELECT subscription_status,
COUNT (customer_id) as repeat_buyers
FROM c_retails
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10) What is the revenue contribution of each age group?
SELECt * FROM c_retails;

SELECT age_group, SUM(purchase_amount) as total_revenue
FROM c_retails
GROUP BY age_group
ORDER BY total_revenue desc;



